### ISSUE TITLE
Template substitutions without braces have incorrect ranges

### ISSUE THREAD

**Issue by akinsho** [UserNobody14/tree-sitter-dart#11]
Currently the grammar is able to pick up a template substitution using `"${example}"` syntax however using `"$example"` syntax returns an incorrect range and does not pick up `example` as an identifier.

The tree shows (for the `${}` syntax)
```
template_substitution [14, 78] - [33, 78])
  identifier [16, 78] - [32, 78])
```
and for `$value`
```
template_substitution [14, 78] - [16, 78])
  identifier_dollar_escaped [15, 78] - [16, 78])
```

**Comment by theHamsta** [comment]
@akinsho the regex for identifier_dollar_escaped looks really suspicious. It works when you just use identifier but this would not consider that you can escape dollar characters.

```js
        identifier: $ => /[a-zA-Z_$][\w$]*/,
        identifier_dollar_escaped: $ => /([a-zA-Z_]|(\\\$))([\w]\\\$)*/,
```
I'll experiment a bit with the regex.

**Comment by theHamsta** [comment]
Found a fix.

This would also work:         `identifier_dollar_escaped: $ => seq(choice(/\$/, /[a-zA-Z_]/), repeat(choice(/\$/, /\w/))),`
