### ISSUE TITLE
String interpolation not highlighted correctly

### ISSUE THREAD

**Issue by theniceboy** [UserNobody14/tree-sitter-dart#13]
Code like
```dart
print("$value");
```
Is not highlighted correctly. `value` should be seen as a variable.

**Comment by akinsho** [comment]
@theniceboy I think this is a duplicate of #11 where I raised a similar issue. I had a look at the code but couldn't figure out how this was happening. @UserNobody14 if you could provide something oversight maybe I could look into it

**Comment by theniceboy** [comment]
Yeah you’re right it is a dup. Sorry about that!
