### ISSUE TITLE
Comments handled incorrectly

### ISSUE THREAD

**Issue by theniceboy** [UserNobody14/tree-sitter-dart#15]
```
return Column(
  children: [
    Container(), //
    Container(),
  ],
);
```
The second container will be recognized as a comment which is incorrect.

**Comment by UserNobody14** [comment]
This issue should be fixed on the latest version!
![image](https://user-images.githubusercontent.com/38988442/169670023-77e0f0a3-4019-41f6-9bbc-55d186d9155a.png)
