### ISSUE TITLE
Indentation not working correctly

### ISSUE THREAD

**Issue by RobertBrunhage** [UserNobody14/tree-sitter-dart#20]
I am using the indentation from treesitter and in dart files the indentation doesn't seem to work at all.

for example when making a `Container` in Flutter this happens.

```dart
Container(
| 
)
```

Instead of 

```dart
Container(
  | 
)
```

Not sure where to turn for these kind of issues, so sorry if this is the wrong place to make an issue :)

**Comment by akinsho** [comment]
@RobertBrunhage I think the best place to raise this is actually https://github.com/nvim-treesitter/nvim-treesitter, that's where the queries for how indentation is handled are actually defined and managed. There aren't many contributors for dart, it's primarily just myself with help from the nvim-treesitter team, but it was actually someone else who added the indentation I haven't looked at the queries for indentation at all. They are very much unloved 😆 .

**Comment by theHamsta** [comment]
Indentation is right now a very experimental feature. It does work correctly in all cases

**Comment by RobertBrunhage** [comment]
Thanks both of you for taking the time, I will open an issue on https://github.com/nvim-treesitter/nvim-treesitter!

What is your current approach for handling this, as I seem to get this kind of indentation working (even without using treesitter).

**Comment by RobertBrunhage** [comment]
Also putting the issue here in case someone else comes across this: https://github.com/nvim-treesitter/nvim-treesitter/issues/1612

**Comment by akinsho** [comment]
@RobertBrunhage https://github.com/dart-lang/dart-vim-plugin is the old school/non-tree-sitter based plugin for dart, it provides indentation, opening package files by pressing `gf` on imports as well as syntax highlighting. You can use it at the same time as treesitter and it will provide working indentation, the tradeoff is both it and treesitter will apply highlighting, tbh in practice it really doesn't make that much discernible difference to the user but it is a bit of a waste, but it's a good enough solution for now.

**Comment by RobertBrunhage** [comment]
@akinsho Yeah I used that before moving to using the built in LSP and now that gives the following indentation haha
![image](https://user-images.githubusercontent.com/26344867/126632689-047abb65-a0a2-46b7-bb16-19a8d0e193c4.png)

```dart
Container(
    |
    )
```

**Comment by akinsho** [comment]
@RobertBrunhage maybe this has to do with the plugin you are using for autopairs. I use `nvim-autopairs` and when I press enter inside `Container(|)` it produces
```
Container(
  |
)
```

**Comment by RobertBrunhage** [comment]
@akinsho Using that one as well and noticed that even `if` cases does this for me. Seems to do this also without an auto pairs plugin.

![image](https://user-images.githubusercontent.com/26344867/126633828-6b4e8c76-ca64-4ecd-b153-dfa21e0461cc.png)

**Comment by akinsho** [comment]
Yeah I can reproduce that one using treesitter indentation. Not sure of a fix though.

**Comment by RobertBrunhage** [comment]
Thanks for taking the time @akinsho! Will see if I can solve it some way, 

will close this issue as I opened it on the treesitter repo 😊
