### ISSUE TITLE
Syntax highlighting is broken due to assuming assignable_selector exists

### ISSUE THREAD

**Issue by Wilfred** [UserNobody14/tree-sitter-dart#24]
As of 7d7fa53d4a9cabf9fee2f8b5d32cb7a4caf82704, `assignable_selector` is no longer in the parse tree. However, the highlights.scm contains this:

https://github.com/UserNobody14/tree-sitter-dart/blame/6a25376685d1d47968c2cef06d4db8d84a70025e/queries/highlights.scm#L121-L122

When I try to load queries.scm with tree-sitter, I get an error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: QueryError { row: 120, column: 1, offset: 1954, message: "assignable_selector", kind: NodeType }'
```

Not sure what the best solution here is: either rename `_assignable_selector` to `assignable_selector` in the grammar, or update the highlighter. In difftastic, I've just commented out this line in queries.scm as I'm not using property highlighting.

**Comment by UserNobody14** [comment]
Fixed! I just updated the highlighter, I think it still looks fine.
