### ISSUE TITLE
Crash on dart files withtout semicolons at the end

### ISSUE THREAD

**Issue by D00mch** [UserNobody14/tree-sitter-dart#28]
Described in main treesitter repo [issue](https://github.com/nvim-treesitter/nvim-treesitter/issues/2961) (treesitter should not crash anyway), but seems to deserved being mention here too.

### To Reproduce
- Create empty file;
- Run :set ft=dart;
- Write any symbol except semicolon.

**Comment by TimWhiting** [comment]
Just installed tree sitter with neovim, not seeing this. Can anyone confirm?

**Comment by momrak** [comment]
I had this for quite some time, but haven't seen it in while now, so might be the root cause has been fixed in some other update?
