### ISSUE TITLE
Infinite loop when parsing a incomplete assignment expression with type argument

### ISSUE THREAD

**Issue by Syndim** [UserNobody14/tree-sitter-dart#40]
The minimal code snippet that can reproduce this bug is:

```dart
final a = StateProvider<T1234567>   // Complete expression is: final a = StateProvider<T1234567>();
```

Running `tree-sitter parse <path/to/above/example.dart>` will cause an infinite loop. Strangely if the length of argument type name is less than 7(i.e. `StateProvider<T123456>`), this issue doesn't happen.

I tried to play around the grammar.js to locate the issue, and it looks it's related this rule in postfix_expression:

```javascript
        _postfix_expression: $ => choice(
          // Commenting out the rule below will resolve this issue            
          seq(
                $._primary,
                repeat(
                    $.selector
                )
            ),
            $.postfix_expression
        ),
```

Any idea why this expression matches the postfix expression and causes the infinite loop? Thanks!

**Comment by SilverMira** [comment]
Probably facing same issue while using this parser within Neovim, some nvim-cmp suggestions straight up freezes neovim, and pins one of my cores to 100%

**Comment by TimWhiting** [comment]
Fixed in latest commit
