### ISSUE TITLE
Get null question mark for fields

### ISSUE THREAD

**Issue by joshpetit** [UserNobody14/tree-sitter-dart#44]
Wouldn't be possible to add support for some identifier for null fields? Types such as "String?" Don't include the question mark in the parsing.

**Comment by TimWhiting** [comment]
I'll take a look at this soon.

**Comment by TimWhiting** [comment]
It should be directly after type_identifiers in the latest commit.

**Comment by joshpetit** [comment]
Same day delivery woww tytyvm
