### ISSUE TITLE
Easier/cleaner way to write tree-sitter grammar

### ISSUE THREAD

**Issue by mingodad** [UserNobody14/tree-sitter-dart#76]
Here https://mingodad.github.io/lua-wasm-playground/ there is an easier/cleaner way to write tree-sitter grammars like `Dart` (select `Tree-sitter-ebnf-generator-Dart` from `Examples` then click `Run` to see a full commented out `grammar.js` from the `EBNF` variant describng the grammar in `
Input Text (arg[1])`).

I hope it can be helpful !

**Comment by UserNobody14** [comment]
This is cool, but I'm not sure how helpful it is, since the given bnf grammars are themselves generated from our json grammars. I played around with it a little and it seemed a tad buggy too. Gonna close this issue for now.

**Comment by mingodad** [comment]
Yes it's not a real parser but a bunch of regex search/replace but it proves that another simpler/cleaner syntax to describe grammars for tree-sitter is viable.
Thanks for your feedback !
