### ISSUE TITLE
Hidden/inaccessible nodes

### ISSUE THREAD

**Issue by akinsho** [UserNobody14/tree-sitter-dart#8]
Hi :wave:,

Thanks for creating this grammar btw :pray: it's been super helpful as a basis for getting some highlighting in nvim-treesitter/nvim-treesitter. Recently I think with a commit aimed at fixing a nested comment issue quite a few nodes were hidden. Specifically `const/var/final` seem to have been hidden so trying to access these in a highlight query no longer works. This means we are unable to highlight these keywords. I could very well be missing something about how else to access these but adding them to an `@keyword` highlight query errors indicating that the nodes can't be found

This ends up looking like this: 
![treesitter-grammar-dart](https://user-images.githubusercontent.com/22454918/89100951-95164600-d3f3-11ea-80b4-4aead56d22a1.png)

I think being able to highlight these would be great for an editor but as I'm not sure why they were hidden I wanted to raise this issue to discuss this, rather than just trying to make a PR without knowing why or if they can be "unhidden"

**Comment by akinsho** [comment]
@UserNobody14 any idea why these are now hidden? can I expose them again?

**Comment by TimWhiting** [comment]
I'm not sure why @UserNobody14 made these hidden. If you want to make a pull request, go ahead and make them visible, and update the tests to make sure that nothing breaks and I'll take a look at it. I think in general we want to make sure the output of tree-sitter parse is readable, and doesn't contain too many unrelated details. However, I think knowing whether something is const / final / var could make it more readable. Please feel free to make any highlighting related pull requests. I don't have much time right now to spend on this personally, but could definitely review / merge pull requests.

**Comment by theHamsta** [comment]
@akinsho Just for your information: for making the nodes visible you have to remove their leading underscore in grammar.js and run tree-sitter generate

**Comment by akinsho** [comment]
Thanks @theHamsta that bit's done just seems to break a lot of tests which I'm updating 🤞🏿

**Comment by akinsho** [comment]
@TimWhiting I've tweaked the grammar to make `const_builtin`, `var_builtin` and `final_builtin` visible but two of the tests keep failing. I think the comments failing relates to why they were hidden in the first place but I have no idea as neither of them use or reference `final` or `const`.

```
  1. Get and set identifiers:
    (program (class_definition (identifier) (class_body (method_signature (func
tion_signature (type_identifier) (identifier) (formal_parameter_list))) (functi
on_body (block (ERROR (function_signature (type_identifier) (ERROR) (identifier
) (formal_parameter_list))) (expression_statement (assignment_expression (assig
nable_expression (identifier)) (identifier))) (ERROR) (expression_statement (as
signment_expression (assignable_expression (identifier)) (identifier))) (return
_statement (identifier)))))))

  2. documentation comment 1:
    (program (comment) (ERROR (type_identifier) (identifier) (ERROR) (documenta
tion_comment)))

  3. documentation comment 2:
    (program (comment) (ERROR (type_identifier) (identifier)))

  4. documentation comment 3:
    (program (comment) (inferred_type) (initialized_identifier_list (initialize
d_identifier (identifier))) (MISSING ";") (ERROR (identifier) (multiplicative_o
perator)))
npm ERR! Test failed.  See above for more details.
```

**Comment by TimWhiting** [comment]
Don't worry about those, those tests were failing prior to your changes

**Comment by akinsho** [comment]
I *think* i've tackled most of the nodes I was referring to in a few different PRs so will close this #9 #10 (for reference)
